### ISSUE TITLE
Consider adding typings

### ISSUE THREAD

**Issue by wrumsby** [SBoudrias/mem-fs#13]
I've added TypeScript typings for `mem-fs` in DefinitelyTyped/DefinitelyTyped#24434

Would you consider providing typings for this module? Alternatively if you don't want to do that, could the information about the typings be provided in the project `README`.

I'm happy to contribute PRs with these changes, but didn't want to make a PR for something of no interest to the project.

**Comment by SBoudrias** [comment]
Hey @wrumsby,

I'm open to add a note to the readme, but I'm not really interested in adding typings directly.

**Comment by askvortsov1** [comment]
Has this position changed by any chance? The typings in DefinitelyTyped are outdated, but since this package is so small, rewriting it in TypeScript wouldn't be too challenging (and would prevent further need to maintain typings separately).

**Comment by SBoudrias** [comment]
Ah yes, I'm open to migrate to TS. I don't plan to work on this myself, but I'm happy to support a PR handling this.
