### ISSUE TITLE
intent of 'change' event?

### ISSUE THREAD

**Issue by olsonpm** [SBoudrias/mem-fs#5]
In lines 39-40 on [index.js](https://github.com/SBoudrias/mem-fs/blob/master/index.js#L39-L40)

```JavaScript
  Store.prototype.add = function (file) {
    store[file.path] = file;
    this.emit('change');
    return this;
  };
```

I'm assuming `this.emit('change')` is meant to indicate the internal store object has been modified.

If this is true, then `Store.prototype.get` should also emit a change event due to the `load` function modifying the internal store.

I created a few branches:
 - [change-event-bug](https://github.com/olsonpm/mem-fs/tree/change-event-bug)
 - [change-event-bug-fix](https://github.com/olsonpm/mem-fs/tree/change-event-bug-fix)

If it's not a bug, please explain the intent so I understand the code better.

Thanks much

**Comment by SBoudrias** [comment]
The intent is to signify a file content have changed. In this case we're not 100% positive the file did change, but we know there's a high change it did.

**Comment by olsonpm** [comment]
Gotcha.  Thanks much.
