### ISSUE TITLE
Add a Method to Check If a File Is Loaded

### ISSUE THREAD

**Issue by jpotterm** [SBoudrias/mem-fs#6]
Currently there is no way to check if a file is loaded into the memory store. The `get` method only works to check for files that don't exists on disk _or_ in mem-fs.

I propose adding a method called `exists` or `loaded` that returns a boolean indicating if the file is currently present in mem-fs.

**Comment by SBoudrias** [comment]
What is the use case?

**Comment by jpotterm** [comment]
I'm trying to make a Yeoman generator that deletes obsolete files from the destination directory. So during the `install` phase I loop through the files in the destination directory and want to check if they've been loaded into mem-fs. If they're loaded then that means the generator wants them there, otherwise they can be deleted.

I tried checking `this.fs.exists` but that always returns `true` since the files exist on disk. I'd like to be able to check something like `this.fs.store.loaded`.

**Comment by SBoudrias** [comment]
Why not simply delete everything in the folder then?

**Comment by jpotterm** [comment]
Because I'd like to be able to live update a running Django web app during development. If I delete the whole directory the app will crash. If I only delete unnecessary files then it will seamlessly reload the files that have changed.

My specific use case may be esoteric, but it seems like useful functionality for an in memory filesystem to be able to tell you if a file exists or not.

**Comment by askvortsov1** [comment]
This can probably be closed with #17
