### ISSUE TITLE
Incorrect use of Vinyl#base

### ISSUE THREAD

**Issue by shannonmoeller** [SBoudrias/mem-fs#7]
I believe that `file.base` is being set incorrectly. In the [source](https://github.com/SBoudrias/mem-fs/blob/master/index.js#L17-L19):

```js
file = new File({
    cwd: process.cwd(),
    base: path.basename(filepath),
    ...
```

According to the [documentation](https://www.npmjs.com/package/vinyl#file), `file.base` is intended to be a directory and `file.basename` is the file's basename. Setting `file.base` to the basename of the file results in an incorrect value being returned from the [`file.relative` getter](https://github.com/gulpjs/vinyl/blob/master/index.js#L171).

I ran into this issue while attempting to create a utility that would override `mem-fs-editor`'s `.commit()` method to generate a zip file using [`gulp-zip`](http://npm.im/gulp-zip).

**Comment by shannonmoeller** [comment]
In case it's helpful, here's my (wip) use case:

```
Generator.prototype._writeFiles = function() {
    var fs = this.fs;

    fs.commit = function(filters, done) {
        var stream = this.store
            .stream()
            .pipe(through.obj(function (file, enc, cb) {
                // Don't process deleted file who haven't been commited yet.
                if (file.state === 'modified' || (file.state === 'deleted' && !file.isNew)) {
                    this.push(file);
                }

                cb();
            }))
            .pipe(through.obj(function(file, enc, cb) {
                file.base = file.cwd;
                this.push(file);
                cb();
            }));

        return filters
            .reduce(
                function(a, b) { return a.pipe(b); },
                stream
            )
            .pipe(zip('foo.zip'))
            .pipe(through.obj(function(file, enc, cb) {
                console.log(file);
                cb();
            }))
            .on('finish', done);
    };

    writeFiles.apply(this, arguments);
};
```

**Comment by SBoudrias** [comment]
@shannonmoeller sound like you're right. Please send a PR to fix this :)

**Comment by SBoudrias** [comment]
Hey, can you let me know if that's fixing your issue?

**Comment by shannonmoeller** [comment]
That did it! Thanks. I was planning to submit a pr this weekend. You beat me to it.
